import "./globals.css";
import logo from "../assets/logo.svg";
import type { Metadata } from "next";
import { Montserrat, Oxanium } from "next/font/google";
import Image from "next/image";
export const metadata: Metadata = {
  title: "NLW RocketSeat",
  description: "Generated by create next app",
};

//fontss
const oxanium = Oxanium({
  weight: ["500", "600"],
  subsets: ["latin"],
  variable: "--font-oxanium",
});

const montserrat = Montserrat({
  weight: ["400", "600"],
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${oxanium.variable} ${montserrat.variable}`}>
      <body className="w-full bg-[url(/background.png)] bg-no-repeat bg-top sm:bg-right-top min-h-screen bg-gray-900 content-center relative">
        <main className="w-fit m-auto p-2">
          <Image
            className="w-[108.5] h-[30] not-md:m-auto"
            src={logo}
            alt="devstage-logo"
          />
          {children}
        </main>

        <footer className="absolute bottom-0 h-1 bg-linear-to-r from-[#4B7FCD] to-[#8A61EA] w-full"></footer>
      </body>
    </html>
  );
}
